[tool.poetry]
name = "tiny"
version = "0.1.0"
description = "URL Shortener with QR Code generation"
authors = ["Harsh Mishra"]
readme = "README.md"
package-mode = false  

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
flask = "^3.0.0"
pymongo = "^4.6.0"
python-dotenv = "^1.0.1"
qrcode = "^8.2"
pillow = "^10.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
