runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v8
      env:
        ISSUE_NUMBER: ${{ inputs.issue_number }}
      with:
        script: |
          const issue_number = parseInt(process.env.ISSUE_NUMBER, 10);

          await github.issues.createComment({
            ...context.repo,
            issue_number,
            body: "👋, Thank you for opening this issue! We will look into it as soon as possible."
          });
