name: "Format Issue Title"

on:
  issues:
    types: [opened, edited]
permissions:
  issues: write

jobs:
  format_title:
    runs-on: ubuntu-latest
    steps:
      - name: Format issue title
        uses: recursivezero/action-club/.github/actions/format-issue-title@v0.2.57
        with:
          prefix: ${{ vars.PROJECT_PREFIX }}
